[package]
name = "variables"
version = "1.1.0"
authors = ["Bora Guven <guvenbe@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
